SERVER-MODES:
  HCF: true
  KITMAP: false
  UHCF: false
  SOUP: false

RELATION_COLOR:
  TEAMMATE: "&2"
  ENEMY: "&c"

CLASSES:
  ROGUE: true
  ARCHER: true
  BARD: true
  MINER: true

  MINER-HEIGHT: 35

POINTS:
  POINTS-KILL: 2
  POINTS-DEATH: 2 # -2
  POINTS-KOTH: 25
  POINTS-CITADEL: 100