SERVER-MODES:
  HCF: true
  KITMAP: false
  UHCF: false
  SOUP: false

LICENSE-KEY: ""

OVERWORLD:
  WARZONE: 500
  CLAIMING: 1000
  BORDER: 2500

SPAWN-LOCATION:
  X: 0
  Y: 100
  Z: 0
  WORLD: "world"
  YAW: 0
  PITCH: 0

NETHER:
  WARZONE: 250
  BORDER: 1500

MAX-FACTION-SIZE: 5

RELATION-COLOR:
  TEAMMATE: "&2"
  ENEMY: "&c"
  ALLY: "&9"
  ARCHER-TAG: "&e"

STARTING-BALANCE: 250
STARTING-PVP-TIMER: 60 # MINUTES (leave 0 to disable)
ENTER-CLAIM-WHILE-PVP-TIMER: true # If this is true, you can enter only your claim with PvP Timer.

CHAT-FORMAT:
  FORMAT: "%team%%rank%%player%&7: &f%s" # %rank% will automatically be hooked into your permissions plugin.
  FORMAT-TEAM: "&e[%relationColor%%name%&e] " #This is for %team%

TEAM-DTR:
  PER-PLAYER: 1.01
  DEATH-DTR: 1.0
  MAX-DTR: 10
  MIN-DTR: -0.99
  REGEN-PER-MIN: 0.1
  REGEN: 45 # minutes
  LOW-DTR: 1.0 # low dtr is the color down below
  COLOR:
    RAIDABLE: "&4"
    LOW-DTR: "&e"
    NORMAL: "&a"
  SYMBOL:
    DTR-FREEZE: "&c■"
    REGENERATING: "&a▲"
    NORMAL: "&a◀"

TIMERS:
  COMBAT:
    TIME: 30 #30 seconds
  ENDERPEARL:
    TIME: 15 #15 seconds
  GOLDEN-APPLE:
    TIME: 30
  ARCHER-TAG:
    TIME: 10

POINTS:
  POINTS-KILL: 2
  POINTS-DEATH: 2 # -2
  POINTS-KOTH: 25
  POINTS-CITADEL: 100