SERVER-MODES:
  HCF: true
  KITMAP: false
  UHCF: false
  SOUP: false

RELATION-COLOR:
  TEAMMATE: "&2"
  ENEMY: "&c"
  ALLY: "&9"

STARTING-BALANCE: 250

CHAT-FORMAT:
  FORMAT: "%team%%rank%%player%&7: &f%s" # %rank% will automatically be hooked into your permissions plugin.
  FORMAT-TEAM: "&e[%relationColor%%name%&e] " #This is for %team%

TEAM-DTR:
  PER-PLAYER: 1.1
  DEATH-DTR: 1.0
  MAX-DTR: 10
  MIN-DTR: -0.99
  REGEN-PER-MIN: 0.1
  REGEN: 45 # minutes
  LOW-DTR: 1.0 # low dtr is the color down below
  COLOR:
    RAIDABLE: "&4"
    LOW-DTR: "&e"
    NORMAL: "&a"
  SYMBOL:
    DTR-FREEZE: "&c■"
    REGENERATING: "&a▲"
    NORMAL: "&a◀"

CLASSES:
  ROGUE: true
  ARCHER: true
  BARD: true
  MINER: true

  MINER-HEIGHT: 35

POINTS:
  POINTS-KILL: 2
  POINTS-DEATH: 2 # -2
  POINTS-KOTH: 25
  POINTS-CITADEL: 100